#!/bin/bash

DIR_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
cd "$DIR_PATH";

OBJCPP_FILES="src/*.mm";
BUILD_FILES="$OBJCPP_FILES";

OBJ_OUTPUT="build/cocoawindowing.o";
OUTPUT="build/libcocoawindowing.a";

clang++ -c $BUILD_FILES -o $OBJ_OUTPUT;
libtool -static $OBJ_OUTPUT -o $OUTPUT;

rm $OBJ_OUTPUT;